global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: shortener-api
    static_configs:
      - targets: ["shortener-api:8080"]
    metrics_path: /metrics

  - job_name: shortener-redirect
    static_configs:
      - targets: ["shortener-redirect:8080"]
    metrics_path: /metrics
