<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Shortener.Redirect</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shortener.Application\Shortener.Application.csproj" />
    <ProjectReference Include="..\Shortener.Infrastructure\Shortener.Infrastructure.csproj" />
    <ProjectReference Include="..\Shortener.Contracts\Shortener.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
  </ItemGroup>

</Project>
