<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Shortener.Domain\Shortener.Domain.csproj" />
    <ProjectReference Include="..\Shortener.Contracts\Shortener.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.10" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>Shortener.Application</RootNamespace>
  </PropertyGroup>

</Project>
