<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Shortener.Application\Shortener.Application.csproj" />
    <ProjectReference Include="..\Shortener.Domain\Shortener.Domain.csproj" />
    <ProjectReference Include="..\Shortener.Contracts\Shortener.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="MaxMind.Db" Version="4.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.41" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>Shortener.Infrastructure</RootNamespace>
  </PropertyGroup>

</Project>
